### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for AR

### ISSUE THREAD

**Issue by josh-zhu** [dukGuo/valle-audiodec#1]
do_tts
    ar.load_state_dict(ar_ckpt['model'])
  File "module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for AR:
	Unexpected key(s) in state_dict: "lm_model.transformer.h.0.attn.bias", "lm_model.transformer.h.0.attn.masked_bias", "lm_model.transformer.h.1.attn.bias", "lm_model.transformer.h.1.attn.masked_bias", "lm_model.transformer.h.2.attn.bias", "lm_model.transformer.h.2.attn.masked_bias", "lm_model.transformer.h.3.attn.bias", "lm_model.transformer.h.3.attn.masked_bias", "lm_model.transformer.h.4.attn.bias", "lm_model.transformer.h.4.attn.masked_bias", "lm_model.transformer.h.5.attn.bias", "lm_model.transformer.h.5.attn.masked_bias", "lm_model.transformer.h.6.attn.bias", "lm_model.transformer.h.6.attn.masked_bias", "lm_model.transformer.h.7.attn.bias", "lm_model.transformer.h.7.attn.masked_bias", "lm_model.transformer.h.8.attn.bias", "lm_model.transformer.h.8.attn.masked_bias", "lm_model.transformer.h.9.attn.bias", "lm_model.transformer.h.9.attn.masked_bias", "lm_model.transformer.h.10.attn.bias", "lm_model.transformer.h.10.attn.masked_bias", "lm_model.transformer.h.11.attn.bias", "lm_model.transformer.h.11.attn.masked_bias"

**Comment by dukGuo** [comment]
please check your `transformers` version, which should be 4.25.1

**Comment by josh-zhu** [comment]
thanks, solved
