### ISSUE TITLE
请教训练参数配置

### ISSUE THREAD

**Issue by xinkez** [dukGuo/valle-audiodec#6]
你好，请问你训练这组模型的时候，训练参数分别是多少？例如：
batch size，learning rate，grad_accu，grad_clip，优化器用的是哪个，非常感谢。

**Comment by dukGuo** [comment]
ar：
bs 3，lr 0.001，acc 10，grad_clip默认值，优化器adamW
nar：
bs 5，lr 0.0005，acc 10，grad_clip默认值，优化器adamW

微调是学习率为原始的十分之一

**Comment by xinkez** [comment]
> ar： bs 3，lr 0.001，acc 10，grad_clip默认值，优化器adamW nar： bs 5，lr 0.0005，acc 10，grad_clip默认值，优化器adamW
> 
> 微调是学习率为原始的十分之一

非常感谢。我在看您的infer_tts.py代码的时候，发现pos_ids是这样实现的，

pos_ids= np.asarray(list(range(semantic_len + 1)) + list(range(acoustic_len)))

这样的话，
例如：semantic_len=2，acoustic_len=3
得到pos_ids = [0, 1, 2, 0, 1, 2]，但我理解是不是应该是pos_ids = [0, 1, 2, 3, 4, 5]，
请指正，谢谢。

**Comment by dukGuo** [comment]
两个模态使用分别的位置编码可以提高模型的性能，在推理的时候过长的文本也不会影响音频序列前半部分的生成

**Comment by xinkez** [comment]
> 两个模态使用分别的位置编码可以提高模型的性能，在推理的时候过长的文本也不会影响音频序列前半部分的生成

谢谢。

那训练阶段，也需要使用这样的位置编码方式，对吧？
那这样的话，训练forward时，position_ids中pad的部分，对应的值应该设置为多少？

**Comment by dukGuo** [comment]
pad 为0  在计算loss时会mask

**Comment by xinkez** [comment]
> pad 为0 在计算loss时会mask

谢谢。

我在处理wenetspeech4tts数据的时候，发现仍然存在一些音频中有两个说话人，请问您在训练模型的时候，重新清洗过这类数据吗？

**Comment by dukGuo** [comment]
没有做特殊处理，少量的多说话人对最终效果影响不大

**Comment by xinkez** [comment]
感谢你的回答。还有两个问题，想请教，拜谢。
1、训练阶段，音频是否需要做“音量归一化”？
2、能分享下您训练的loss曲线吗？或者训练到收敛阶段，loss是多少？

**Comment by dukGuo** [comment]
1. 我们做了归一化
2. ar loss在2.5左右，nar loss在3.5左右

**Comment by xinkez** [comment]
> 1. 我们做了归一化
> 2. ar loss在2.5左右，nar loss在3.5左右

您好，按照您的建议，ar阶段的训练结果是正常的；但nar阶段训练，一直不收敛（loss基本保持不变）。我目前的训练策略如下：
nar训练阶段，每个step按照均匀分布随机选择1个codec layer进行训练，一个batch中选择的codec layer index是相同的；
此外，audio prompt的选择是audio长度的25%～50%（抽样也是均匀分布）。

请帮忙指正一下问题，或者提些建议，非常感谢。

**Comment by dukGuo** [comment]
我们mask的比例比较低，前rand(1,340)帧mask掉作为prompt

**Comment by xinkez** [comment]
> ar： bs 3，lr 0.001，acc 10，grad_clip默认值，优化器adamW nar： bs 5，lr 0.0005，acc 10，grad_clip默认值，优化器adamW
> 
> 微调是学习率为原始的十分之一

感谢回复。

我训练nar阶段，使用您上面提到的学习率配置（lr 0.0005），一开始用的是固定学习率（lr 0.0005），但模型不收敛，后面我修改为warmup的方式，模型可以收敛（loss收敛到3.8左右），但测试性能不是很好。和您确认一下，nar阶段的训练使用的是固定学习率 还是 特殊设计的学习率衰减方式？

**Comment by dukGuo** [comment]
用的warmup，60k步后按余弦降低到300k步
